# Generated by Django 3.2.9 on 2021-11-27 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 9, 1, 23, 378574))),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('excerpt', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('day', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 9, 1, 23, 378574))),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.blogcategory')),
            ],
        ),
    ]
