# Generated by Django 3.2.9 on 2021-11-27 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20211127_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 15, 51, 1, 659119)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 15, 51, 1, 659119)),
        ),
    ]
