# Generated by Django 3.2.9 on 2021-11-27 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211127_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 16, 35, 12, 695634)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 16, 35, 12, 695634)),
        ),
    ]
