# Generated by Django 3.2.9 on 2021-11-27 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20211127_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 16, 36, 59, 640315)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 16, 36, 59, 640315)),
        ),
    ]
