# Generated by Django 3.2.9 on 2022-01-28 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20220128_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 19, 53, 2, 129135)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(blank=True, default='2022-01-28 19:53:02'),
        ),
    ]
