# Generated by Django 3.2.9 on 2021-11-27 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedmail',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 18, 20, 33, 774765)),
        ),
    ]
