# Generated by Django 3.2.9 on 2021-11-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 18, 18, 37, 335484)),
        ),
    ]
