# Generated by Django 3.2.9 on 2022-01-28 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contactmessage_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 19, 23, 17, 79453)),
        ),
    ]
