# Generated by Django 3.2.9 on 2022-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_contactmessage_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='sent_date',
            field=models.DateTimeField(default='2022-01-28 19:29:37'),
        ),
    ]
